import textwrap
import re

"""Module: 07 · Gaussian Mixture Models"""

TOPIC_NAME   ="Gaussian Mixture Models"
DISPLAY_NAME = "07 · Gaussian Mixture Models"
ICON         = "📊"
SUBTITLE     = "Soft probabilistic clustering using mixtures of Gaussians"

THEORY = r"""
## 07 · Gaussian Mixture Models (GMM)

---

### The Limitation of Hard Clustering

K-Means assigns every point to exactly one cluster — **hard assignment**. But
real data rarely respects such crisp boundaries. A point sitting between two
clusters plausibly belongs to both. A cluster with a stretched, elliptical
shape cannot be captured by K-Means' spherical Voronoi cells.

Gaussian Mixture Models replace hard assignments with **soft probabilistic
membership**. Instead of asking "which cluster does this point belong to?",
a GMM asks "what is the probability this point was generated by each cluster?"

---

### What Is a Mixture Model?

A **mixture model** assumes the observed data was generated by one of K latent
components. The full data distribution is:

    p(x) = sum_{k=1}^{K}  pi_k * N(x; mu_k, Sigma_k)

where:
- pi_k  is the **mixing weight** of component k,  sum_k pi_k = 1,  pi_k >= 0
- N(x; mu_k, Sigma_k)  is the multivariate Gaussian for component k
- mu_k  is the mean vector;  Sigma_k  is the covariance matrix

The multivariate Gaussian density:

    N(x; mu, Sigma) = (2*pi)^{-p/2} * |Sigma|^{-1/2}
                      * exp( -1/2 * (x-mu)^T Sigma^{-1} (x-mu) )

A GMM is a weighted sum of K Gaussian "bells", each at a different position,
with a different size and orientation.

---

### The Generative Story

    1. Choose a component: z ~ Categorical(pi_1, ..., pi_K)
    2. Draw a point from that component: x | z=k ~ N(mu_k, Sigma_k)

The variable z is **latent** — never observed. The GMM problem is to infer
the parameters theta = {pi_k, mu_k, Sigma_k} and the latent assignments z
from the observed data x alone.

---

### The EM Algorithm for GMMs

Maximum likelihood cannot be solved in closed form because the log-likelihood
has a sum inside the log:

    log p(X | theta) = sum_i  log( sum_k  pi_k * N(x_i; mu_k, Sigma_k) )

The **Expectation-Maximisation (EM)** algorithm iterates two steps:

---

#### E-Step: Compute Responsibilities

For each point x_i and component k, compute the **responsibility** — the
posterior probability that component k generated x_i:

    r_{ik} = p(z=k | x_i, theta)
           = pi_k * N(x_i; mu_k, Sigma_k)
             ------------------------------------------
             sum_j  pi_j * N(x_i; mu_j, Sigma_j)

This is Bayes' theorem. The denominator normalises so that sum_k r_{ik} = 1.
The (n x K) responsibility matrix R is the "soft assignment table".

---

#### M-Step: Update Parameters

Using responsibilities as fractional weights:

    N_k = sum_i r_{ik}                         (effective cluster size)

    pi_k_new = N_k / n                         (mixing weight)

    mu_k_new = (1/N_k) * sum_i r_{ik} * x_i   (responsibility-weighted mean)

    Sigma_k_new = (1/N_k) * sum_i r_{ik} * (x_i - mu_k_new)(x_i - mu_k_new)^T

Each parameter is a responsibility-weighted average across the entire dataset.

---

#### Full EM Algorithm

    Input: data X (n x p), number of components K

    1. Initialise:
       mu_k  from K-Means++ or random data points
       Sigma_k = I for all k
       pi_k = 1/K for all k

    2. Repeat until convergence:
       E-step: r_{ik} = pi_k N(x_i; mu_k, Sigma_k) / sum_j pi_j N(x_i; mu_j, Sigma_j)
       M-step: update N_k, pi_k, mu_k, Sigma_k as above

    3. Log-likelihood: L = sum_i log( sum_k pi_k N(x_i; mu_k, Sigma_k) )

    4. Stop if |L_new - L_old| < epsilon

EM **monotonically increases the log-likelihood** at every iteration.
It converges to a local maximum (not necessarily global).

---

### A Worked Example (1D, 2 Components)

Data: x = [1.0, 1.5, 6.0, 6.5, 2.0]

Initialise: pi_1=pi_2=0.5, mu_1=1.0, mu_2=6.0, sigma_1=sigma_2=1.0

E-step for x_1 = 1.0:
    N(1.0; mu=1.0, sigma=1) = (1/sqrt(2*pi)) * exp(0) = 0.3989
    N(1.0; mu=6.0, sigma=1) = (1/sqrt(2*pi)) * exp(-12.5) ~= 0.0000

    r_{11} = (0.5 * 0.3989) / (0.5*0.3989 + 0.5*0.0000) ~= 1.000
    r_{12} ~= 0.000

After E-step on all 5 points:
    N_1 ~= 3.0  (points 1, 2, 5)
    N_2 ~= 2.0  (points 3, 4)

M-step:
    mu_1_new = (1.0 + 1.5 + 2.0) / 3.0 = 1.50
    mu_2_new = (6.0 + 6.5) / 2.0       = 6.25

After one iteration the means have moved to the true cluster centres.

---

### Covariance Structure

**Spherical:**  Sigma_k = sigma_k^2 * I
    Circular clusters. Equivalent to soft K-Means as sigma_k -> 0.

**Diagonal:**  Sigma_k = diag(sigma_{k1}^2, ..., sigma_{kp}^2)
    Axis-aligned ellipses. Independent feature variances per cluster.

**Full:**  Sigma_k = arbitrary p x p positive definite matrix
    Arbitrarily oriented ellipsoids. Most expressive; needs p(p+1)/2 params.

**Tied:**  Sigma_k = Sigma (same for all k)
    All clusters have identical shape; fewer parameters.

---

### Log-Likelihood and Convergence

    L(theta) = sum_i  log( sum_k  pi_k * N(x_i; mu_k, Sigma_k) )

Properties:
- L is non-decreasing every EM iteration (guaranteed by Jensen's inequality).
- Converges to a local maximum — run multiple restarts, keep the best.
- Degenerate solutions: if one component collapses (sigma -> 0), L -> infinity.
  Guard by enforcing a minimum variance (add epsilon * I to each Sigma_k).

---

### Model Selection: AIC and BIC

The log-likelihood always increases with more components. Penalise complexity:

    AIC = -2 * L(theta) + 2 * |theta|
    BIC = -2 * L(theta) + |theta| * log(n)

where |theta| is the number of free parameters:
    Diagonal GMM:  K*(2p) + (K-1)
    Full GMM:      K*p*(p+3)/2 + (K-1)  (approx)

Lower AIC / BIC = better. BIC penalises more strongly (log n vs 2) and
tends to select simpler models on large datasets.

---

### GMM as a Soft Version of K-Means

K-Means is a limiting case of GMM:
    - Spherical covariance with equal mixing weights (pi_k = 1/K)
    - Let sigma_k^2 -> 0 (infinitely tight Gaussians)
    - Responsibilities r_{ik} become hard 0/1 assignments
    - M-step mean update becomes the K-Means centroid update

GMMs strictly generalise K-Means by adding soft assignments, elliptical shapes,
varying cluster sizes, and a proper probabilistic interpretation.

---

### GMM vs Other Methods

| Property                 | K-Means           | GMM                          | DBSCAN           |
|--------------------------|-------------------|------------------------------|------------------|
| Assignment type          | Hard              | Soft (probabilistic)         | Hard + noise     |
| Cluster shape            | Spherical         | Elliptical (full covariance) | Arbitrary        |
| Varying cluster sizes    | No                | Yes (pi_k and Sigma_k)       | Yes              |
| Probabilistic output     | No                | Yes (full posterior)         | No               |
| Model selection          | Elbow/Silhouette  | AIC / BIC                    | Not needed       |
| Handles outliers         | No                | Weakly (low responsibility)  | Yes (noise = -1) |
| Density estimation       | No                | Yes                          | No               |
| Degeneracy risk          | Low               | High (singular covariance)   | None             |

---

### Key Takeaways

1. A GMM models data as a weighted sum of K Gaussians. Each component has
   its own mean mu_k, covariance Sigma_k, and mixing weight pi_k.

2. Fitting uses EM: E-step computes soft responsibilities r_{ik}; M-step
   updates parameters using responsibility-weighted statistics. EM
   monotonically increases the log-likelihood but may find a local maximum.

3. Covariance type (spherical, diagonal, full, tied) trades off expressiveness
   vs parameter count. Full covariance is most flexible but needs more data.

4. Use AIC or BIC to select K. Regularise Sigma_k to avoid degeneracy.

5. A fitted GMM is an explicit density estimator: it supports likelihood
   scoring, sampling new synthetic points, and Bayesian classification.
"""


OPERATIONS = {

    "▶ Run: GMM EM From Scratch": {
        "description": "Full EM for a 2D GMM with diagonal covariance. Every iteration prints responsibilities, parameter updates, and log-likelihood until convergence on a 3-component mixture.",
        "code": r'''
import math, random
random.seed(42)

def blob(cx, cy, sx, sy, n):
    return [(cx + random.gauss(0,sx), cy + random.gauss(0,sy)) for _ in range(n)]

data = (blob(0.0, 0.0, 0.6, 0.6, 30)
      + blob(5.0, 0.0, 0.8, 0.4, 30)
      + blob(2.0, 4.0, 0.5, 0.7, 30))
n, K, p = len(data), 3, 2
true_labels = [0]*30 + [1]*30 + [2]*30

# Diagonal Gaussian PDF
def gpdf(x, mu, var):
    det  = var[0] * var[1]
    norm = 1.0 / ((2*math.pi)**(p/2) * math.sqrt(max(det, 1e-300)))
    arg  = sum((x[j]-mu[j])**2 / max(var[j],1e-10) for j in range(p))
    return norm * math.exp(-0.5 * arg)

def compute_ll(data, mus, vars_, pis):
    return sum(math.log(max(sum(pis[k]*gpdf(xi,mus[k],vars_[k]) for k in range(K)),1e-300))
               for xi in data)

# Initialise
random.seed(1)
idx   = random.sample(range(n), K)
mus   = [list(data[i]) for i in idx]
vars_ = [[1.0, 1.0]]*K
pis   = [1.0/K]*K
prev_ll = -1e18
R = [[0.0]*K for _ in range(n)]

print(f"GMM EM  |  n={n}, K={K}, dim={p}")
print()
print(f"  {'Iter':>5}  {'Log-likelihood':>16}  {'delta-LL':>12}  pi values")
print("  " + "-"*65)

for it in range(1, 51):
    # E-step
    for i, xi in enumerate(data):
        nums  = [pis[k]*gpdf(xi,mus[k],vars_[k]) for k in range(K)]
        denom = sum(nums) or 1e-300
        R[i]  = [v/denom for v in nums]
    # M-step
    Nk    = [max(sum(R[i][k] for i in range(n)), 1e-6) for k in range(K)]
    pis   = [nk/n for nk in Nk]
    mus   = [[sum(R[i][k]*data[i][j] for i in range(n))/Nk[k] for j in range(p)]
             for k in range(K)]
    vars_ = [[max(sum(R[i][k]*(data[i][j]-mus[k][j])**2 for i in range(n))/Nk[k], 0.01)
              for j in range(p)] for k in range(K)]
    ll  = compute_ll(data, mus, vars_, pis)
    dll = ll - prev_ll
    if it <= 10 or it % 10 == 0 or abs(dll) < 1e-6:
        pi_str = " ".join(f"{pi:.3f}" for pi in pis)
        print(f"  {it:>5}  {ll:>16.4f}  {dll:>12.6f}  [{pi_str}]")
    if abs(dll) < 1e-6 and it > 2:
        print(f"\n  Converged at iteration {it}")
        break
    prev_ll = ll

print()
print("Final parameters:")
for k in range(K):
    print(f"  C{k+1}: pi={pis[k]:.4f}  mu=[{mus[k][0]:.3f},{mus[k][1]:.3f}]  "
          f"sigma=[{math.sqrt(vars_[k][0]):.3f},{math.sqrt(vars_[k][1]):.3f}]")

# Purity check
from collections import Counter
assigns = [max(range(K), key=lambda k: R[i][k]) for i in range(n)]
pur = sum(Counter(true_labels[i] for i in range(n) if assigns[i]==k).most_common(1)[0][1]
          for k in range(K)) / n
print(f"\nHard assignment purity: {pur:.1%}")
''',
        "runnable": True,
    },

    "▶ Run: Soft vs Hard Assignments": {
        "description": "Show the difference between GMM soft probabilistic assignments and K-Means hard assignments on overlapping clusters. Prints the responsibility table for boundary points.",
        "code": r'''
import math, random
random.seed(7)

data = ([(random.gauss(0,1), random.gauss(0,1)) for _ in range(25)]
      + [(random.gauss(3,1), random.gauss(0,1)) for _ in range(25)])
n, K = len(data), 2
true_labels = [0]*25 + [1]*25

def g1d(x, mu, var):
    return (1/math.sqrt(2*math.pi*max(var,1e-10))) * math.exp(-0.5*(x-mu)**2/max(var,1e-10))
def g2d(x, mu, var):
    return g1d(x[0],mu[0],var[0]) * g1d(x[1],mu[1],var[1])

mus   = [list(data[0]), list(data[-1])]
vars_ = [[1.0,1.0],[1.0,1.0]]
pis   = [0.5,0.5]

for _ in range(30):
    R = []
    for xi in data:
        nums  = [pis[k]*g2d(xi,mus[k],vars_[k]) for k in range(K)]
        denom = sum(nums) or 1e-300
        R.append([v/denom for v in nums])
    Nk    = [max(sum(R[i][k] for i in range(n)),1e-6) for k in range(K)]
    pis   = [nk/n for nk in Nk]
    mus   = [[sum(R[i][k]*data[i][j] for i in range(n))/Nk[k] for j in range(2)]
             for k in range(K)]
    vars_ = [[max(sum(R[i][k]*(data[i][j]-mus[k][j])**2 for i in range(n))/Nk[k],0.01)
              for j in range(2)] for k in range(K)]

# K-Means
def ed(a,b): return math.sqrt((a[0]-b[0])**2+(a[1]-b[1])**2)
centres = [list(data[0]), list(data[-1])]
for _ in range(20):
    hard = [min(range(K), key=lambda k: ed(xi,centres[k])) for xi in data]
    for k in range(K):
        mem = [data[i] for i in range(n) if hard[i]==k]
        if mem: centres[k] = [sum(m[j] for m in mem)/len(mem) for j in range(2)]

# Sort by ambiguity (|r0 - r1| smallest = most uncertain)
ambig = [abs(R[i][0]-R[i][1]) for i in range(n)]
sorted_idx = sorted(range(n), key=lambda i: ambig[i])

print("GMM Soft vs K-Means Hard Assignments")
print(f"K=2 overlapping clusters  |  n={n}")
print()
print("Most ambiguous boundary points:")
print(f"  {'i':>4}  {'x':>6}  {'y':>6}  {'r(C1)':>8}  {'r(C2)':>8}  GMM  KM  True  Note")
print("  " + "-"*62)
for i in sorted_idx[:12]:
    xi = data[i]
    r0, r1 = R[i]
    note = "boundary" if abs(r0-r1)<0.3 else ""
    diff = "differ" if (0 if r0>r1 else 1) != hard[i] else ""
    print(f"  {i:>4}  {xi[0]:>6.2f}  {xi[1]:>6.2f}  {r0:>8.4f}  {r1:>8.4f}  "
          f"C{(0 if r0>r1 else 1)+1}   C{hard[i]+1}   C{true_labels[i]+1}    {note} {diff}")

print()
print("Certain points:")
print(f"  {'i':>4}  {'x':>6}  {'y':>6}  {'r(C1)':>8}  {'r(C2)':>8}  GMM")
print("  " + "-"*48)
for i in sorted_idx[-5:]:
    xi = data[i]; r0, r1 = R[i]
    print(f"  {i:>4}  {xi[0]:>6.2f}  {xi[1]:>6.2f}  {r0:>8.4f}  {r1:>8.4f}  C{(0 if r0>r1 else 1)+1}")

print()
print("Boundary points have responsibilities near [0.50, 0.50].")
print("K-Means assigns these firmly to one cluster, discarding uncertainty.")
print("GMM preserves the ambiguity for downstream probabilistic reasoning.")
''',
        "runnable": True,
    },

    "▶ Run: AIC and BIC for Component Selection": {
        "description": "Fit GMMs with K = 1 to 8 components. Compute AIC and BIC for each K. Identify the optimal number of components from the penalised likelihood scores.",
        "code": r'''
import math, random
random.seed(99)

def blob(cx,cy,sx,sy,n):
    return [(cx+random.gauss(0,sx), cy+random.gauss(0,sy)) for _ in range(n)]

data = blob(0,0,0.7,0.7,40) + blob(5,0,0.8,0.5,40) + blob(2,4,0.6,0.7,40)
n    = len(data)

def g2d(x, mu, var):
    det  = var[0]*var[1]
    norm = 1.0 / ((2*math.pi)*math.sqrt(max(det,1e-300)))
    return norm*math.exp(-0.5*sum((x[j]-mu[j])**2/max(var[j],1e-10) for j in range(2)))

def fit_gmm(data, K, seed=0):
    random.seed(seed); n=len(data)
    idx   = random.sample(range(n), K)
    mus   = [list(data[i]) for i in idx]
    vars_ = [[0.8,0.8]]*K; pis=[1.0/K]*K; prev=-1e18
    R     = [[0.0]*K for _ in range(n)]
    for _ in range(60):
        for i,xi in enumerate(data):
            nums=[pis[k]*g2d(xi,mus[k],vars_[k]) for k in range(K)]
            d=sum(nums) or 1e-300; R[i]=[v/d for v in nums]
        Nk=[max(sum(R[i][k] for i in range(n)),1e-6) for k in range(K)]
        pis=[nk/n for nk in Nk]
        mus=[[sum(R[i][k]*data[i][j] for i in range(n))/Nk[k] for j in range(2)] for k in range(K)]
        vars_=[[max(sum(R[i][k]*(data[i][j]-mus[k][j])**2 for i in range(n))/Nk[k],0.02)
                for j in range(2)] for k in range(K)]
        ll=sum(math.log(max(sum(pis[k]*g2d(xi,mus[k],vars_[k]) for k in range(K)),1e-300))
               for xi in data)
        if abs(ll-prev)<1e-5 and _>3: break
        prev=ll
    return ll

# K*(2p) + (K-1) parameters for diagonal 2D GMM
npar = lambda K: K*4 + (K-1)

print(f"AIC and BIC Model Selection  |  n={n}  |  True K=3")
print()
print(f"  {'K':>3}  {'Log-Lik':>12}  {'#params':>8}  {'AIC':>12}  {'BIC':>12}  Mark")
print("  " + "-"*58)

results = []
for K in range(1, 9):
    best = max(fit_gmm(data, K, seed=s) for s in range(3))
    np_  = npar(K)
    aic  = -2*best + 2*np_
    bic  = -2*best + np_*math.log(n)
    results.append((K, best, np_, aic, bic))

best_aic = min(results, key=lambda r: r[3])[0]
best_bic = min(results, key=lambda r: r[4])[0]
for K, ll, np_, aic, bic in results:
    marks = []
    if K == best_aic: marks.append("AIC min")
    if K == best_bic: marks.append("BIC min")
    print(f"  {K:>3}  {ll:>12.3f}  {np_:>8}  {aic:>12.3f}  {bic:>12.3f}  {', '.join(marks)}")

print(f"\n  AIC selects K={best_aic}  |  BIC selects K={best_bic}  |  True K=3")
print()
print("BIC penalises complexity more (log n vs 2 per parameter).")
print("For large n, BIC tends to select fewer components than AIC.")
''',
        "runnable": True,
    },

    "▶ Run: GMM vs K-Means on Elliptical Clusters": {
        "description": "Compare GMM (full 2x2 covariance) and K-Means on elongated rotated elliptical clusters. K-Means struggles; GMM adapts its covariance to match cluster shapes.",
        "code": r'''
import math, random
random.seed(55)

def ellipse_blob(cx, cy, angle_deg, sig_long, sig_short, n):
    a = angle_deg*math.pi/180
    pts = []
    for _ in range(n):
        u = random.gauss(0, sig_long); v = random.gauss(0, sig_short)
        pts.append((cx + u*math.cos(a) - v*math.sin(a),
                    cy + u*math.sin(a) + v*math.cos(a)))
    return pts

data = (ellipse_blob(0, 0,  30, 2.5, 0.4, 30)
      + ellipse_blob(6, 2, 120, 2.5, 0.4, 30)
      + ellipse_blob(3, 5,  75, 2.0, 0.5, 30))
n = len(data); K = 3
true_labels = [0]*30+[1]*30+[2]*30

def ed(a,b): return math.sqrt((a[0]-b[0])**2+(a[1]-b[1])**2)

def kmeans(data, K, seed=0):
    random.seed(seed)
    C = [list(data[i]) for i in random.sample(range(len(data)),K)]
    A = [0]*len(data)
    for _ in range(100):
        A = [min(range(K), key=lambda k: ed(xi,C[k])) for xi in data]
        for k in range(K):
            mem = [data[i] for i in range(len(data)) if A[i]==k]
            if mem: C[k]=[sum(m[j] for m in mem)/len(mem) for j in range(2)]
    return A

def mat2inv(C):
    d = C[0][0]*C[1][1]-C[0][1]*C[1][0]
    if abs(d)<1e-10: return None,None
    return [[C[1][1]/d,-C[0][1]/d],[-C[1][0]/d,C[0][0]/d]], d

def gfull(x, mu, Ci, ld):
    dx=[x[j]-mu[j] for j in range(2)]
    mah=sum(dx[i]*Ci[i][j]*dx[j] for i in range(2) for j in range(2))
    return math.exp(-0.5*(2*math.log(2*math.pi)+ld+mah))

def fit_full(data, K, seed=0):
    random.seed(seed); n=len(data)
    mus=[list(data[i]) for i in random.sample(range(n),K)]
    Cs=[[[1.0,0.0],[0.0,1.0]]]*K; pis=[1.0/K]*K; reg=0.05; prev=-1e18
    R=[[0.0]*K for _ in range(n)]
    for _it in range(80):
        invs=[]; lds=[]
        for k in range(K):
            Cr=[[Cs[k][i][j]+(reg if i==j else 0) for j in range(2)] for i in range(2)]
            inv,det=mat2inv(Cr)
            if inv is None or det<=0: inv=[[1,0],[0,1]]; det=1.0
            invs.append(inv); lds.append(math.log(max(det,1e-300)))
        for i,xi in enumerate(data):
            nums=[pis[k]*gfull(xi,mus[k],invs[k],lds[k]) for k in range(K)]
            d=sum(nums) or 1e-300; R[i]=[v/d for v in nums]
        Nk=[max(sum(R[i][k] for i in range(n)),1e-6) for k in range(K)]
        pis=[nk/n for nk in Nk]
        mus=[[sum(R[i][k]*data[i][j] for i in range(n))/Nk[k] for j in range(2)] for k in range(K)]
        Cs=[[[sum(R[i][k]*(data[i][a]-mus[k][a])*(data[i][b]-mus[k][b])
                  for i in range(n))/Nk[k] for b in range(2)] for a in range(2)] for k in range(K)]
        ll=sum(math.log(max(sum(pis[k]*gfull(xi,mus[k],invs[k],lds[k])
                               for k in range(K)),1e-300)) for xi in data)
        if abs(ll-prev)<1e-5 and _it>5: break
        prev=ll
    return [max(range(K),key=lambda k: R[i][k]) for i in range(n)], Cs, mus

from collections import Counter
def purity(A, tl, K):
    return sum(Counter(tl[i] for i in range(len(A)) if A[i]==k).most_common(1)[0][1]
               for k in range(K)) / len(tl)

best_km = max(purity(kmeans(data,K,seed=s), true_labels, K) for s in range(3))
best_gp, best_Cs, best_mus = 0, None, None
for s in range(3):
    try:
        A, Cs, ms = fit_full(data, K, seed=s)
        p = purity(A, true_labels, K)
        if p > best_gp: best_gp=p; best_Cs=Cs; best_mus=ms
    except: pass

print(f"GMM vs K-Means on Rotated Elliptical Clusters  |  n={n}, K={K}")
print()
print(f"  {'Method':<25}  {'Purity':>8}")
print("  " + "-"*36)
print(f"  {'K-Means':<25}  {best_km:>8.1%}  (spherical cells, bad for ellipses)")
print(f"  {'GMM full covariance':<25}  {best_gp:>8.1%}  (adapts to ellipse orientation)")
print()
if best_Cs:
    print("Learned covariance (aspect ratio and tilt of each component ellipse):")
    for k in range(K):
        C=best_Cs[k]; tr=C[0][0]+C[1][1]; det_=C[0][0]*C[1][1]-C[0][1]**2
        disc=max(0,(tr/2)**2-det_)
        l1=tr/2+math.sqrt(disc); l2=max(tr/2-math.sqrt(disc),1e-6)
        aspect=math.sqrt(l1/l2)
        angle=0.5*math.atan2(2*C[0][1],C[0][0]-C[1][1])*180/math.pi
        print(f"  C{k+1}: mu=[{best_mus[k][0]:>5.2f},{best_mus[k][1]:>5.2f}]  "
              f"aspect={aspect:.2f}  tilt={angle:.1f} deg")
''',
        "runnable": True,
    },

    "▶ Run: GMM Density Estimation and Sampling": {
        "description": "Fit a GMM and use it as an explicit density estimator. Evaluate p(x) at any point and generate new synthetic samples from the fitted distribution.",
        "code": r'''
import math, random
random.seed(11)

def blob(cx,cy,sx,sy,n):
    return [(cx+random.gauss(0,sx), cy+random.gauss(0,sy)) for _ in range(n)]

data = blob(0,0,0.6,0.6,30) + blob(4,0,0.7,0.4,30) + blob(2,3,0.5,0.6,30)
n, K = len(data), 3

def g2d(x,mu,var):
    det=var[0]*var[1]; norm=1.0/((2*math.pi)*math.sqrt(max(det,1e-300)))
    return norm*math.exp(-0.5*sum((x[j]-mu[j])**2/max(var[j],1e-10) for j in range(2)))

# Fit GMM
random.seed(1)
idx   = random.sample(range(n), K)
mus   = [list(data[i]) for i in idx]
vars_ = [[0.8,0.8]]*K; pis=[1.0/K]*K
R     = [[0.0]*K for _ in range(n)]
for _ in range(60):
    for i,xi in enumerate(data):
        nums=[pis[k]*g2d(xi,mus[k],vars_[k]) for k in range(K)]
        d=sum(nums) or 1e-300; R[i]=[v/d for v in nums]
    Nk=[max(sum(R[i][k] for i in range(n)),1e-6) for k in range(K)]
    pis=[nk/n for nk in Nk]
    mus=[[sum(R[i][k]*data[i][j] for i in range(n))/Nk[k] for j in range(2)] for k in range(K)]
    vars_=[[max(sum(R[i][k]*(data[i][j]-mus[k][j])**2 for i in range(n))/Nk[k],0.02)
            for j in range(2)] for k in range(K)]

def density(x):
    return sum(pis[k]*g2d(x,mus[k],vars_[k]) for k in range(K))

print("GMM Density Estimation and Sampling")
print(f"Fitted K={K} components on n={n} points")
print()
for k in range(K):
    print(f"  C{k+1}: pi={pis[k]:.3f}  mu=[{mus[k][0]:.2f},{mus[k][1]:.2f}]  "
          f"sigma=[{math.sqrt(vars_[k][0]):.2f},{math.sqrt(vars_[k][1]):.2f}]")

print()
test_pts = [(0.0,0.0,"cluster 1 centre"), (4.0,0.0,"cluster 2 centre"),
            (2.0,3.0,"cluster 3 centre"), (2.0,0.0,"between C1 and C2"),
            (10.0,10.0,"far outside")]
print(f"  {'Point':<22}  {'p(x)':>12}  {'log p(x)':>12}  Note")
print("  " + "-"*60)
for (x,y,note) in test_pts:
    px=density((x,y)); lpx=math.log(max(px,1e-300))
    print(f"  ({x:.1f}, {y:.1f}){' '*(13-len(f'({x:.1f}, {y:.1f})'))}"
          f"  {px:>12.6f}  {lpx:>12.4f}  {note}")

# Sampling
def bm_gauss():
    u=random.random() or 1e-9; v=random.random()
    return math.sqrt(-2*math.log(u))*math.cos(2*math.pi*v)

def sample_gmm(n_samples):
    out=[]
    for _ in range(n_samples):
        r=random.random(); cum=0; k=0
        for j,pi in enumerate(pis):
            cum+=pi
            if r<=cum: k=j; break
        pt=[mus[k][j]+bm_gauss()*math.sqrt(vars_[k][j]) for j in range(2)]
        out.append((pt,k))
    return out

N_SAM=20
print()
print(f"Generating {N_SAM} samples from the fitted GMM:")
print(f"  {'#':>3}  {'x':>8}  {'y':>8}  {'Component':>14}  {'p(x)':>10}")
print("  " + "-"*50)
for i,(pt,comp) in enumerate(sample_gmm(N_SAM)):
    print(f"  {i+1:>3}  {pt[0]:>8.3f}  {pt[1]:>8.3f}  "
          f"C{comp+1} (pi={pis[comp]:.2f})        {density(tuple(pt)):>10.6f}")

print()
print("Sampling procedure:")
print("  Step 1: draw component k from Categorical(pi_1,...,pi_K)")
print("  Step 2: draw x from N(mu_k, Sigma_k) for the chosen k")
''',
        "runnable": True,
    },

}


# Dedent all operation code strings — they're indented inside the dict literal,
# so each line has ~20 leading spaces. textwrap.dedent removes the common indent,
# producing clean left-aligned code that runs without IndentationError.
for _op in OPERATIONS.values():
    _op["code"] = textwrap.dedent(_op["code"]).strip()

# ─────────────────────────────────────────────────────────────────────────────
# RENDER OPERATIONS (Streamlit)
# ─────────────────────────────────────────────────────────────────────────────
def render_operations(st, scripts_dir=None, main_script=None):
    """Render all operations with code display and optional run buttons."""
    import streamlit as st  # local import so module stays importable without st

    st.markdown("---")
    st.subheader("⚙️ Operations")

    if scripts_dir is None:
        scripts_dir = None
    if main_script is None:
        main_script = None

    scripts_available = main_script.exists()

    if "tok_step_status"  not in st.session_state:
        st.session_state.tok_step_status  = {}
    if "tok_step_outputs" not in st.session_state:
        st.session_state.tok_step_outputs = {}

    for op_name, op_data in OPERATIONS.items():
        with st.expander(f"▶️ {op_name}", expanded=False):
            st.markdown(f"**{op_data['description']}**")
            st.markdown("---")
            st.code(op_data["code"], language=op_data.get("language", "python"))


# ─────────────────────────────────────────────────────────────────────────────
# UTILITY
# ─────────────────────────────────────────────────────────────────────────────
# render_operations() has been removed.  app.py owns all Streamlit rendering
# via its own render_operation() helper and strips callables from topic dicts
# inside load_topics_for() anyway — so a local render function is never called.

def _strip_ansi(text):
    return re.compile(r'\x1b\[[0-9;]*m').sub('', text)


# ─────────────────────────────────────────────────────────────────────────────
# CONTENT EXPORT
# ─────────────────────────────────────────────────────────────────────────────

def get_content():
    """Return all content for this topic module — single source of truth."""
    visual_html   = ""
    visual_height = 400
    try:
        from Unsupervised_Learning.visuals.gmm_visual import (   # ← match your exact folder casing
            VISUAL_HTML,
            VISUAL_HEIGHT,
        )
        visual_html   = VISUAL_HTML.encode("utf-8", "surrogatepass").decode("utf-8", "ignore")
        visual_height = VISUAL_HEIGHT
    except Exception as e:
        import warnings
        warnings.warn(f"Could not load visual: {e}", stacklevel=2)

    return {
        "display_name":  DISPLAY_NAME,
        "icon":          ICON,
        "subtitle":      SUBTITLE,
        "theory":        THEORY,
        "visual_html":   visual_html,
        "visual_height": visual_height,
        "complexity":    None, # COMPLEXITY,
        "operations":    OPERATIONS,
    }

